# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b355206a6c7929506b77cf6e594551101f0c1e3cb4146300b0ec5217dcb271b0dc187d72b6568f53538f7cf64a51a100ae22ea00c3cb75da173e347b2124f55

test:
  secret_key_base: 81b9ec3e7b7c566ce86fde240e6240e3112c5dee35019dc8cd0ba34a2bb2aa70d0dd2928f03aa6d5ad6e15c139005a3b1e254f091b18fb799f5bd16d800f2b0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
